services:
  vector:
    volumes:
      - ./volumes/logs/vector.coolify.yml:/etc/vector/vector.yml:ro,z
      - ${DOCKER_SOCKET_LOCATION}:/var/run/docker.sock:ro,z

  # Keep DB dependency on Vector healthy check to preserve startup order
  db:
    depends_on:
      vector:
        condition: service_healthy
      analytics:
        condition: service_healthy

