services:
  vector:
    volumes:
      # Mount directory so /etc/vector/vector.yml is present as a file
      - ./volumes/logs:/etc/vector:ro,z
      - ${DOCKER_SOCKET_LOCATION:-/var/run/docker.sock}:/var/run/docker.sock:ro,z

  # Keep DB dependency on Vector healthy check to preserve startup order
  db:
    depends_on:
      vector:
        condition: service_healthy
      analytics:
        condition: service_healthy

  # Coolify runs a reverse proxy; remove host port mappings that rely on envs
  kong:
    ports: []

  supavisor:
    ports: []
