services:
  vector:
    volumes:
      # Mount config directory to a custom path to avoid conflicts with /etc/vector
      - ./volumes/logs:/etc/vector-config:ro,z
      - ${DOCKER_SOCKET_LOCATION:-/var/run/docker.sock}:/var/run/docker.sock:ro,z
    environment:
      VECTOR_CONFIG: /etc/vector-config/vector.yml
    command:
      [
        "--config",
        "/etc/vector-config/vector.yml"
      ]

  # Keep DB dependency on Vector healthy check to preserve startup order
  db:
    depends_on:
      vector:
        condition: service_healthy
      analytics:
        condition: service_healthy

  # Coolify runs a reverse proxy; remove host port mappings that rely on envs
  kong:
    ports: []

  supavisor:
    ports: []
